# questions.py

def get_questions():
    return {
        "forest": "Does it live in the forest?",
        "savanna": "Does it live in the savanna?",
        "mountain": "Does it live in the mountains?",
        "grassland": "Does it live in the grasslands?",
        "river": "Does it live near rivers?",
        "four_legs":"Does it have four_legs",
        "two_legs":"Does it have two_legs",
        "eight_legs":"Does it have eight_legs",
        "no_legs":"Does it have no_legs",
        "wetland": "Does it live in wetlands?",
        "marine": "Does it live in the sea?",
        "urban": "Does it live in urban areas?",
        "desert_dweller": "Does it live in the desert?",
        "underground": "Does it live underground?",
        "aquatic": "Does it live in the water?",
        "forest_or_urban": "Can it live in forests or urban areas?",
        "farm": "Does it live on farms?",
        "herbivore": "Is it a herbivore?",
        "carnivore": "Is it a carnivore?",
        "omnivore": "Is it an omnivore?",
        "insect_eater": "Does it eat insects?",
        "fish_eater": "Does it eat fish?",
        "seed_eater": "Does it eat seeds?",
        "wood_eater": "Does it eat wood?",
        "grazer": "Is it a grazer?",
        "snake_hunter": "Does it hunt snakes?",
        "swimmer": "Can it swim?",
        "burrower": "Does it dig or burrow?",
        "arboreal": "Does it live in trees?",
        "nocturnal": "Is it active at night?",
        "diurnal": "Is it active during the day?",
        "slithers": "Does it move by slithering on the ground?",
        "venomous": "Is it venomous or does it have poison?",
        "solitary": "Does it prefer to live alone?",
        "social": "Does it live in groups or with others?",
        "domestic": "Is it domestic?",
        "wild": "Is it wild?",
        "pet": "Is it kept as a pet?",
        "mammal": "Is it a mammal?",
        "bird": "Is it a bird?",
        "reptile": "Is it a reptile?",
        "insect": "Is it an insect?",
        "invertebrate": "Is it an invertebrate?",
        "crocodilian": "Is it a crocodilian?",
        "shell": "Does it have a shell?",
        "horns": "Does it have horns?",
        "tail": "Does it have a tail?",
        "wings": "Does it have wings?",
        "hooves": "Does it have hooves?",
        "fur": "Does it have fur?",
        "feathered": "Does it have feathers?",
        "scales": "Does it have scales?",
        "colorful": "Is it colorful?",
        "brown": "Is it brown?",
        "white": "Is it white?",
        "yellow": "Is it yellow?",
        "red_breast": "Does it have a red breast?",
        "black_white": "Is it black and white?",
        "camouflage": "Is it camouflaged?",
        "striped_face": "Does it have a striped face?",
        "long_neck": "Does it have a long neck?",
        "long_legs": "Does it have long legs?",
        "short_wings": "Does it have short wings?",
        "long_tusks": "Does it have long tusks?",
        "trunk_like_snout": "Does it have a trunk-like snout?",
        "fast": "Is it fast?",
        "slow": "Is it slow?",
        "strong": "Is it strong?",
        "graceful": "Is it graceful?",
        "gentle": "Is it gentle?",
        "intelligent": "Is it intelligent?",
        "cute": "Is it considered cute?",
        "playful": "Is it playful?",
        "nocturnal_singer": "Does it sing at night?",
        "vocal": "Is it vocal or noisy?",
        "songbird": "Is it a songbird?",
        "tool_user": "Does it use tools?",
        "pack": "Does it live in packs?",
        "colony_nester": "Does it nest in colonies?",
        "monogamous": "Is it monogamous?",
        "migratory": "Does it migrate seasonally?",
        "territorial": "Is it territorial?",
        "burrow_dweller": "Does it live in burrows?",
        "endangered": "Is it endangered?",
        "cold_blooded": "Is it cold-blooded?",
        "warm_blooded": "Is it warm-blooded?",
        "semi_aquatic": "Is it semi-aquatic?",
        "arboreal_dweller": "Does it live mostly in trees?",
        "flying": "Can it fly?",
        "pollinator": "Is it a pollinator?",
        "bioluminescent": "Does it glow or emit light?",
        "stinger": "Does it have a stinger?",
        "venomous": "Is it venomous?",
        "many_legs": "Does it have many legs?",
        "segmented_body": "Does it have a segmented body?",
        "pincers": "Does it have pincers?",
        "sound_produces": "Does it produce sound?",
        "jumping": "Can it jump?",
        "fast_runner": "Is it a fast runner?",
        "basks_in_sun": "Does it bask in the sun?",
        "camouflaged": "Is it camouflaged?",
        "hunter": "Is it a hunter?",
        "burrow_dweller_larvae": "Do its larvae live underground?",
        "beetle_family": "Is it a beetle?",
        "pig_family": "Is it from the pig family?",
        "canid": "Is it from the dog family?",
        "rodent_family": "Is it from the rodent family?",
        "dog_like": "Is it dog-like?",
        "bird_family": "Is it from the bird family?",
        "meows":"Does it make a meowing sound?",
        "wings": "Can it fly using wings?",
        "flippers": "Does it use flippers to swim?",
        "scales": "Does it have a scaly body?",
        "crustacean": "Is it an animal with a hard shell and jointed legs that lives in water?",
        "arachnid": "Is it an animal with eight legs and no antennae?",  
        "filter_feeder": "Does it get its food by filtering tiny things from water?",
        "mollusk": "Is it a soft-bodied animal, often with a hard shell?",
        "lays_eggs": "Does it reproduce by laying eggs?",
        "ruminant": "Is it an animal that chews cud?",
        "docile": "Is it generally calm and easy to handle?",
        "clucks": "Does it make a clucking sound?",
        "broody_possible": "Can it sit on eggs to hatch them?"
    }

